### ISSUE TITLE
RSolr::Error::Http - 413 Request Entity Too Large

### ISSUE THREAD

**Issue by awead** [psu-stewardship/archivesphere#13]
This is happening here: https://github.com/psu-stewardship/archivesphere/blob/develop/spec/controllers/http_header_auth_spec.rb#L25

**Comment by mjgiarlo** [comment]
What does the request object look like?

**Comment by hectorcorrea** [comment]
It seems that starting in Blacklight 4.6.3 we can configure the use of HTTP POST (instead of HTTP GET) to work around issues with very large URIs. See this post: https://github.com/projecthydra/hydra/wiki/Use-HTTP-POST-for-Solr-requests

We are currently on Blacklight 4.5 so I'll wait to test this once we upgrade the version of Blacklight that we are using in ArchiveSphere.

**Comment by mjgiarlo** [comment]
:+1:
